#!/usr/bin/env node
const { execSync } = require("child_process");
let log = console.log;

//console.log(__dirname)
//return

// Note: stdio: pipe is to prevent any output getting printed to console directly, yikes!!
const options = { stdio: "pipe" };

try {
  let deleteFolder = execSync("rm -rf temp-generatemd-dontdelete", options).toString();
  let createNewFolder = execSync("mkdir temp-generatemd-dontdelete", options).toString();
  try {
    let cdAndBackupIndexHtmlFile = execSync("cd sahilrajput03 && cp index.html index.htlm", options).toString();
  } catch (error) {
    log("The build will use last backup of html file.");
  }

  try {
    let deleteOnlyHtmlFilesInSahilRajput03 = execSync("cd sahilrajput03 && rm *.html 2> /dev/null", options).toString();
    let deleteOnlyHtmlFilesInMore = execSync("cd sahilrajput03/more && rm *.html 2> /dev/null", options).toString();
  } catch (error) {
    console.log("booo:", error.message);
  }

  try {
    let generateStaticFilesLog = execSync(
      "generate-md --layout ./custom-layout-mypersonalized-dontdelete --input ./sahilrajput03 --output ./temp-generatemd-dontdelete",
      options
    ).toString();
  } catch (error) {
    console.log("boo:1.3:", error.message);
    if (error.message.includes("generate-md: command not found")) {
      console.log("We're now installing generate-md i.e., npm i markdown-styles");
      execSync("npm i markdown-styles", options).toString();
    }
  }

  let greetSuccess = execSync(
    "echo Thanks for using generate-md util, files generated by generate-md successfully!",
    options
  ).toString();
  // let t = execSync("cp 2> /dev/null", options).toString();
  // log("bala", t);
  try {
    let copyFilesToSahilRajput03 = execSync(
      "cp -r temp-generatemd-dontdelete/* sahilrajput03/ 2> /dev/null",
      options
    ).toString();
  } catch (error) {
    console.log("Boo:2: Didn't copy files to sahilrajput03 from temp-generated-dontdelete folder.", error.message);
  }

  let generatingAllMarkdownsHtmlFile = execSync("cd sahilrajput03 && node nodescript.js", options).toString();
  let generatingMoreMarkdownsHtmlFile = execSync("cd sahilrajput03/more && node nodescript.js", options).toString();
  let gettingBacupFromEarlierIndexFile = execSync("cd sahilrajput03 && cp index.htlm index.html", options).toString();

  let makingLegitCommit = execSync("cd sahilrajput03 && echo Legit Commit >> LegitCommit.txt", options).toString();
  let push = execSync(
    "cd sahilrajput03 && git add . && git commit -m 'Update ~Sahil.' && git push",
    options
  ).toString();
  // log(push)
  log("🥳︎ Check repo @ https://github.com/sahilrajput03/sahilrajput03.github.io");
  //
  // let list2 = execSync('rm -rf test/* test/.* ', options).toString()
} catch (error) {
  console.log("Boo:3:", error.message);
}
